services:
- type: web
  repo: https://github.com/drestr30/livekit-agents

  # Change this to the path containing your Dockerfile
  rootDir: voice-agent

  name: agent-example
  runtime: docker

  # Free plan is not available for private services
  plan: free

  # Environment variables are stored in a group
  # created in the Render dashboard.
  envVars:
  - fromGroup: livekit-agent
  region: virginia

  # 300s is the standard allowed maximum. Talk to render.com support if you need this increased.
  #maxShutdownDelaySeconds: 300

  # Sane defaults
  # scaling:
  #   minInstances: 1
  #   maxInstances: 4
  #   targetCPUPercent: 60
  #   targetMemoryPercent: 60
version: "1"